version: "3.9"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - 8082:8080
    volumes:
      - ./openapi/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
  proxy:
    image: nginx:mainline-alpine
    container_name: "proxy-nginx"
    ports:
      - ${PORT-8084}:8084
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - swagger-ui
