version: '3'
services:
  springapp:
    build: .
    container_name: springapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
    ports:
      - "8000:8080"
    restart: always
    depends_on:
      - db
  db:
    image: postgres:alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dfkthrf17
    ports:
      - "5435:5432"
    restart: always