-- MySQL Script generated by MySQL Workbench
-- Wed Apr 14 10:24:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS "blog" ;

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS "blog";
-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
-- USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`user`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `blog`.`user` ;
--
--  CREATE TABLE IF NOT EXISTS `blog`.`user` (
--                                               `id` INT NOT NULL AUTO_INCREMENT,
--                                               `name` VARCHAR(16) NOT NULL,
--                                               `first_name` VARCHAR(45) NULL,
--                                               `last_name` VARCHAR(45) NULL,
--                                               `email` VARCHAR(255) NULL,
--                                               `password` VARCHAR(32) NOT NULL,
--                                               `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
--                                               `role` VARCHAR(45) NULL,
--                                               PRIMARY KEY (`id`));

DROP TABLE IF EXISTS "user" ;

CREATE TABLE IF NOT EXISTS "user" (
                                      id SERIAL NOT NULL,
                                      name VARCHAR(16) NOT NULL,
                                      first_name VARCHAR(45) NULL,
                                      last_name VARCHAR(45) NULL,
                                      email VARCHAR(255) NULL,
                                      password VARCHAR(32) NOT NULL,
                                      create_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                      role VARCHAR(45) NULL,
                                      PRIMARY KEY (id));